# Generated by Django 5.2.16 on 2026-07-30 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barberos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Galería',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración del servicio en minutos.')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requiere_confirmacion', models.BooleanField(default=False, help_text='Ej: la tintura requiere confirmación previa del barbero.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CON', 'Confirmado'), ('REC', 'Rechazado'), ('CAN', 'Cancelado'), ('COM', 'Completado')], default='PEN', max_length=3)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='barberos.barbero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clientes.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='clientes.servicio')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('SMS', 'SMS'), ('PUSH', 'Notificación push')], max_length=4)),
                ('mensaje', models.CharField(max_length=300)),
                ('programada_para', models.DateTimeField()),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRO', 'Programada'), ('ENV', 'Enviada'), ('FAL', 'Fallida')], default='PRO', max_length=3)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.turno')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['programada_para'],
            },
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('barbero', 'fecha', 'hora_inicio'), name='unico_turno_barbero_horario'),
        ),
    ]
